### ISSUE TITLE
USD 印鈔戰況

### ISSUE THREAD

**Issue by davidlatwe** [MoonShineVFX/reveries-config#4]
_From @davidlatwe on September 29, 2017 8:4_

不斷聽聞 USD 要在 windows 上 build 起來難如登天，緣此於這成立戰情室，分享第一線戰況消息。

Linux 的消息也可以在這一同發布。

_Copied from original issue: MoonShineVFX/core#4_

**Comment by davidlatwe** [comment]
USD windows maya build
===

**[USD build club 說明](https://github.com/vfxpro99/usd-build-club/wiki/USD-on-Windows)**

### 資源

[win10 虛擬機](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
[MSVC2015](http://www.kunal-chowdhury.com/2015/07/download-visualstudio-2015.html#buZeHq4yF96q1gmw.97)
[Maya DevKit 設定](http://help.autodesk.com/view/MAYAUL/2017/ENU//?guid=__files_Setting_up_your_build_environment_htm)
[Qt build with msvc2015](https://stackoverflow.com/questions/32848962/how-to-build-qt-4-8-6-with-visual-studio-2015-without-official-support)
[Qt 5.7](https://download.qt.io/official_releases/qt/5.7/5.7.1/)
[Qt 4.8](https://download.qt.io/official_releases/qt/4.8/4.8.7/)


### 注意事項

**Prereqs 的環境變數要確實設定好**

**Qt 4.8.7 要先 build 好，並設定好環境變數  = for Boost**

**Qt 5.7 用 exe 安裝好後，放好位置就不用去理它了  = for USD**

**Maya 目前只支援  2016.5 以上**

**devkit 我用 maya 2017 update 3**

**PTEX 跟 ALEMBIC 的支援要關掉，這兩個目前不會成功**

**BUILD_TESTS 也是關掉**

```
DPXR_BUILD_MAYA_PLUGIN=1
DPXR_ENABLE_PYTHON_SUPPORT=1
DPXR_BUILD_ALEMBIC_PLUGIN=0
DPXR_ENABLE_PTEX_SUPPORT=0
DPXR_BUILD_TESTS=0
```

~## 幹 maya load 不進來~
將 `C:\Program Files\Autodesk\Maya2017\bin\glew.dll` 替換成我們 build 出來的 `glew.dll` 就好了!

**Comment by davidlatwe** [comment]
可以從 Maya 輸出模型到 usd-view 檢視，lambert 的材質顏色會帶過去。
 usd-view 可以檢視滿多資訊，好像會很實用?

不過我目前 build 的這個沒有 alembic 跟 ptex 的支援，要再請教一下大大然後再次嘗試 build 看看。

![](https://i.imgur.com/HY2hmFb.png)

**Comment by davidlatwe** [comment]
前面是以 [vfxpro99/usd-build-club](https://github.com/vfxpro99/usd-build-club) 為基礎，然後我自己 [davidlatwe/usd-build-club](https://github.com/davidlatwe/usd-build-club) 做一咪咪微調 build 起來的，但似乎還是沒有原廠的方便與完整，接下來要換用原廠的方式 build 看看。

**Comment by davidlatwe** [comment]
# Pixar method

成果 : 基本款可以無痛 build，但進階的項目如 Embree 是壞掉的，Houdini 出不來。另外，Ptex 跟 Maya 只能擇一。

平台 : Windows 10 虛擬機 (環境保證乾淨)
版本 : [0.8.0](https://github.com/PixarAnimationStudios/USD/releases)
分支 : Master
修改 : [davidlatwe/USD-85c7a9deee](https://github.com/davidlatwe/USD/tree/85c7a9deeed4befa6f9222e486d385ae2a9cfd77)

###### 修改內容 :
* ###### 增加 `HOUDINI_LIB_DIR`
* ###### 修改 HDF5 的下載網址

---

### 需求

#### Basic :
* Python
* [py-module] pyside, pyopengl, pyd(?)
* CMake    
* NASM
* MSVC2015

#### for Documentation :
* Doxygen [1.8.6](https://sourceforge.net/projects/doxygen/files/) (版本限定)
* GraphViz

#### for Maya :
* Maya 2017 Devkit update 3

#### for Houdini :
* Houdini 16 (這個目前無法 build 出來)

#### for USD Schema Generation :
* [py-module] jinja2, Argparse (裝了，但不知道是否有效果)

#### for Embree Rendering :
* embree (這個目前 build 出來是壞的)

#### for ASCII Parser Editing/Validation :
* win-flex and bison (裝了，但不知道是否有效果)

#### for Malloc Library :
* Jemalloc (還沒看怎麼 install / build)

---

### build CMD

官方有叮嚀使用 msvc2015 dev prompt 要開啟 x64 模式，但似乎不用特別做這一步
```
cd VC & vcvarsall x64
```

切換到 USD 的 git repo
```
cd c:\USD_git\USD
```

##### build good 👍 

* DOC
```
python build_scripts\build_usd.py "c:\USD_build" --doc
```

ptex 和 maya 的支援只能挑一種，原因是 USD 使用的 ptex 版本與 Maya 不同，一起作業會衝突

* PTEX & ALEMBIC (HDF5)
```
python build_scripts\build_usd.py "c:\USD_build" --ptex --alembic --hdf5
```

* MAYA & ALEMBIC (HDF5)
```
python build_scripts\build_usd.py "c:\USD_build" --maya --maya-location "C:\Program Files\Autodesk\Maya2017" --alembic --hdf5
```

---

##### build fail 👎 

**EMBREE**
```
python build_scripts\build_usd.py "c:\USD_build" --embree --embree-location "C:\Program Files\Intel\Embree v2.17.0 x64"
```

build 可以過，但是開啟 usdview 要切換成 embree render 時就會跳下面錯誤
###### (maybe try a embree only clean build ?)
```
Traceback (most recent call last):
  File "E:\USD_build\lib\python\pxr\Usdviewq\mainWindow.py", line 1054, in <lambda>
    self._rendererPluginChanged(pluginType))
  File "E:\USD_build\lib\python\pxr\Usdviewq\mainWindow.py", line 1038, in _rendererPluginChanged
    self._stageView.SetRendererPlugin(plugin)
  File "E:\USD_build\lib\python\pxr\Usdviewq\stageView.py", line 1552, in SetRendererPlugin
    self._renderer.SetRendererPlugin(name)
pxr.Tf.ErrorException:
        Error in 'pxrInternal_v0_8__pxrReserved__::PlugPlugin::_Load' at line 283 in file C:\USD_git\USD\pxr\base\lib\plug\plugin.cpp : 'Load of 'e:/USD_build/plugin/usd/hdEmbree.dll' for 'hdEmbree' failed: 找不到指定的模組。
'
        Error in 'pxrInternal_v0_8__pxrReserved__::UsdImagingGLHdEngine::SetRendererPlugin' at line 957 in file C:\USD_git\USD\pxr\usdImaging\lib\usdImagingGL\hdEngine.cpp : 'Couldn't find plugin named HdEmbreeRendererPlugin'
```

**HOUDINI**

```
python build_scripts\build_usd.py "c:\USD_build" --houdini --houdini-location "C:\Program Files\Side Effects Software\Houdini 16.0.736"
```

Build 過程中就出錯，不知怎解
```
"C:\USD_b\build\USD\install.vcxproj" (default target) (1) ->

"C:\USD_b\build\USD\ALL_BUILD.vcxproj" (default target) (3) ->

"C:\USD_b\build\USD\third_party\houdini\plugin\OP_gusd\OP_gusd.vcxproj" (default target) (4) ->

"C:\USD_b\build\USD\third_party\houdini\lib\gusd\gusd.vcxproj" (default target) (31) ->

(ClCompile target) -> 

  cl : Command line error D8021: invalid numeric argument '/Wno-parentheses' [C:\USD_b\build\USD\third_party\houdini\lib\gusd\gusd.vcxproj]
```

---

### 注意

* 重 build 時，最好把整個 install dir 都清掉，尤其是切換 HDF5 的選項時。

* `/build` 底下的東西如果有刪掉，`/src` 的東西也要刪掉，因為目前 build script 看到 `/src` 那邊有東西就會跳去下一個相依套件的安裝，不會重 build。

* 不管 build 選項如何，build 出來的 docs 都一樣。
